#!/bin/sh

# Extract version bump from commit message
commit_msg=$(git log -1 --pretty=%B)

# Extract version bump using regex
version_bump=$(echo "$commit_msg" | grep -oE '\[(patch|minor|major)\]' | head -n 1)

# If version bump is found, set npm version
if [ -n "$version_bump" ]; then
  npm version "$version_bump" --no-git-tag-version
fi