#!/bin/sh

# Extract version bump from commit message
commit_msg=$(git log -1 --pretty=%B)

# Extract version bump using regex
version_bump=$(echo "$commit_msg" | grep -oE '\[(patch|minor|major)\]' | head -n 1)

# Map version bump to corresponding semantic versioning value
case $version_bump in
  "[patch]")
    new_version="patch"
    ;;
  "[minor]")
    new_version="minor"
    ;;
  "[major]")
    new_version="major"
    ;;
  *)
    new_version="" # No valid version bump found
    ;;
esac

# If a valid version bump is found, set npm version
if [ -n "$new_version" ]; then
  npm version "$new_version" --no-git-tag-version
fi
