name: Automatic Node.js Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      run: |
        curl -sL https://deb.nodesource.com/setup_21.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install -g npm

    - name: Install dependencies
      run: npm install

    - name: Change to package directory
      run: cd ../..

    - name: Execute pre-commit hook
      run: .husky/pre-commit

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        curl -sL https://deb.nodesource.com/setup_21.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install -g npm
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
